############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "Offre de logement"
url = "logement/"
weight = 2

[[main]]
name = "Galerie photos"
url = "photos/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4


# footer menu

[[footer]]
name = "Mentions légales"
url = "logement/"
weight = 2